# Aliases
# alias sc="source ~/.bash_profile"
alias sc="source ~/.zshrc"
alias zenv="code ~/Development/Repos/home/zsh-env ~/.zshrc"
alias zshenv="code ~/.zshrc"
alias codebash="code ~/.bash_profile"
alias dev="cd ~/Development/Repos"
alias docs="cd ~/Documents"
alias home="cd ~"
alias ls='ls -GFhla'
alias ll='ls -la'
alias lsg='ll | grep $1'
alias cd..='cd ..'
alias ..='cd ..'
alias h='history'
alias python="python3"
alias pip="pip3"
alias neo="neo.sh"
alias d="docker"
alias kb="kubectl"
alias k="kubectl"
alias mk="minikube"
alias dc="docker-compose"
alias gs="git status"
alias helm3="helm"
alias prom="open http://localhost:8080 && k -n kube-system port-forward service/prometheus-prometheus 8080:80"
alias ap="ansible-playbook"
alias av="ansible-vault"
alias tf="terraform"
alias is="istioctl"
alias hs='history | grep'
alias kc='kubecolor'
alias gc='gcmsg'
alias kd='kubectl describe'
alias eureka='code ~/Development/Repos/eureka'
